version: '2'

services: 
  mysql:
    image: mariadb
    container_name: etherpad-mysql
    environment:
      MYSQL_DATABASE: 'etherpad'
      MYSQL_USER: 'etherpad'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - /data/bases/etherpad/mysql:/var/lib/mysql
  etherpad:
    build: 
      context: .
      args:
        # proxy for npm & curl
        proxy: ${http_proxy}
    image: rhanka/etherpad
    container_name: etherpad
    ports:
      - "9001:9001"
    volumes:

      - ./settings.json:/opt/etherpad/settings.json
    links:
      - mysql:mysql
    restart: always
